### ISSUE TITLE
Todo list to go public/social

### ISSUE THREAD

**Issue by jebyrnes** [Covid19R/covid19R#3]
- [ ] Amanda/Rami - Make error checks/email failures in covid19R_data: 
      - [ ] matching controlled vocab 
      - [x] correct minimal columns
      - [ ] data is bigger than it was at last update (if not new)
      - [ ] check that date object is date class
      - [ ] check that minimal columns are same type as previously
  - [x] Amanda make the Us data usable for main package
  - [ ] Rami setups up standard (refresh_* and get_info_*) functions in his packages. Let us know when done
  - [x] Rami - sets up covid19R_data cronjob via github action or otherwise
  - [x] Rami unpin the covid19_data repo (yes?)
  - [x] Rami pin the covid19_package_template repo
  - [ ] Jarrett add US, swiss, coronavirus, and italy packages
  - [x] Jarrett works on documentation 
  - [x] Jarrett incorporates beta tester feedback
  - [ ] Each of us write a tweet Tweetthread
  - [ ] Each of us write a blog post somewhere?
  - [ ] Submit covid19R to CRAN?

**Comment by jebyrnes** [comment]
Well, still some todo on this, but, so it goes - time to launch.
